#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller: App\Controller\MainController::index

#app_user_signup:
#    path: /signup
#    controller: App\Controller\UserController::signUp
#    methods: GET|POST

app_login:
    path: /login
    controller: App\Controller\UserController::login

app_logout:
    path: /logout
    controller: App\Controller\UserController::logout

app_signup:
    path: /signup
    controller: App\Controller\UserController::signUp

app_item_men_polos:
    path: /men/polos
    controller: App\Controller\ItemController::menPolos

app_item_men_shirts:
    path: /men/shirts
    controller: App\Controller\ItemController::menShirts

app_item_men_pants:
    path: /men/pants
    controller: App\Controller\ItemController::menPants

app_admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

app_admin_addcheque:
    path: /admin/addcheque
    controller: App\Controller\AdminController::addCheque

app_admin_deletecheque:
    path: /admin/deletecheque/{id}
    controller: App\Controller\AdminController::deleteCheque