#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller: App\Controller\MainController::index

#app_user_signup:
#    path: /signup
#    controller: App\Controller\UserController::signUp
#    methods: GET|POST

app_item_men_polos:
    path: /men/polos
    controller: App\Controller\ItemController::menPolos

app_item_men_shirts:
    path: /men/shirts
    controller: App\Controller\ItemController::menShirts

app_item_men_pants:
    path: /men/pants
    controller: App\Controller\ItemController::menPants